import React from "react";
import type { Metadata } from "next";
import ReferansPageContainer from "@/containers/ReferansPageContainer";

export const metadata: Metadata = {
  title:
    "Referanslar | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};
const ReferanslarPage = () => {
  return (
    <main>
      <ReferansPageContainer />
    </main>
  );
};

export default ReferanslarPage;
