import Link from "next/link";
import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "Referanslar | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};
const ReferanslarPage = () => {
  return <div>ReferanslarPage</div>;
};

export default ReferanslarPage;
