import BlogPageContainer from "@/containers/BlogPageContainer";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title:
    "Blog | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};

const BlogPage = () => {
  return (
    <main>
      <BlogPageContainer />
    </main>
  );
};

export default BlogPage;
