import HomePageContainer from "@/containers/HomePageContainer";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title:
    "Anasayfa | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};
export default function Page() {
  // Header animation

  //
  return (
    <main>
      <HomePageContainer />
    </main>
  );
}
