import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "İletişim | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};
const IletisimPage = () => {
  return <div>IletisimPage</div>;
};

export default IletisimPage;
