import React from "react";
import type { Metadata } from "next";
import YazilimPageContainer from "../../containers/YazilimPageContainer";

export const metadata: Metadata = {
  title:
    "Yazılım | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};
const YazilimPage = () => {
  return (
    <main>
      <YazilimPageContainer />
    </main>
  );
};

export default YazilimPage;
