import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "Yazılım | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};
const YazilimPage = () => {
  return <div>YazilimPage</div>;
};

export default YazilimPage;
