import type { Metadata } from "next";
import React from "react";
export const metadata: Metadata = {
  title:
    "Eğitim | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};
const EgitimPage = () => {
  return <div>EgitimPage</div>;
};

export default EgitimPage;
