import type { Metadata } from "next";
import React from "react";
import EgitimPageContainer from "../../containers/EgitimPageContainer";
export const metadata: Metadata = {
  title:
    "Eğitim | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};
const EgitimPage = () => {
  return (
    <main>
      <EgitimPageContainer />
    </main>
  );
};

export default EgitimPage;
