import type { Metadata } from "next";
import React from "react";
import DanismanlikPageContainer from "../../containers/DanismanlikPageContainer";
export const metadata: Metadata = {
  title:
    "Danışmanlık | DigitalAid | Süreç Yönetim, Dijital Dönüşüm, PaperWork Danışmalık",
  description: "Generated by create next app",
};
const DanismanlikPage = () => {
  return (
    <main>
      <DanismanlikPageContainer />
    </main>
  );
};

export default DanismanlikPage;
